export const ASSET_KEYS = {
  emojiSheet: "emoji_sheet",
  teemoEmotes: "teemo_emotes",
  basicPack: "basic_pack",
  allIcons: "all_icons",
  whiteIcons: "white_icons",
  specialIcons: "special_icons",
  weatherIcons: "weather_icons",
  inventory: "inventory",
  hearts: "hearts",
  inventoryBlocks: "inventory_blocks",
  dialogBig: "dialog_big",
  dialogMedium: "dialog_medium",
  dialogSmall: "dialog_small",
  speechBubble: "speech_bubble",
  squareButtons: "square_buttons",
  smallSquareButtons: "small_square_buttons",
  playButton: "play_button",
  settingsMenu: "settings_menu",
  settingsButtons: "settings_buttons",
  jamDialogMedium: "jam_dialog_medium",
  sfxCropPop: "sfx_crop_pop",
  sfxJump: "sfx_jump",
  sfxLevelClear: "sfx_level_clear",
} as const;

export type AssetKey = (typeof ASSET_KEYS)[keyof typeof ASSET_KEYS];

export const ASSET_PATHS: Record<AssetKey, string> = {
  emoji_sheet: "/assets/sprout/sprites/emoji_sheet.png",
  teemo_emotes: "/assets/sprout/emotes/teemo_emotes.png",
  basic_pack: "/assets/sprout/sprites/basic_pack.png",
  all_icons: "/assets/sprout/icons/all_icons.png",
  white_icons: "/assets/sprout/icons/white_icons.png",
  special_icons: "/assets/sprout/icons/special_icons.png",
  weather_icons: "/assets/sprout/icons/weather.png",
  inventory: "/assets/sprout/inventory/inventory.png",
  hearts: "/assets/sprout/inventory/hearts.png",
  inventory_blocks: "/assets/sprout/inventory/blocks.png",
  dialog_big: "/assets/sprout/dialog/dialog_big.png",
  dialog_medium: "/assets/sprout/dialog/dialog_medium.png",
  dialog_small: "/assets/sprout/dialog/dialog_small.png",
  speech_bubble: "/assets/sprout/dialog/speech_bubble.png",
  square_buttons: "/assets/sprout/buttons/square_26x26.png",
  small_square_buttons: "/assets/sprout/buttons/small_square.png",
  play_button: "/assets/sprout/ui/play_button.png",
  settings_menu: "/assets/sprout/ui/settings.png",
  settings_buttons: "/assets/sprout/ui/settings_buttons.png",
  jam_dialog_medium: "/assets/sprout/jam/premade_dialog_medium.png",
  sfx_crop_pop: "/assets/audio/mixkit-video-game-blood-pop-2361.wav",
  sfx_jump: "/assets/audio/mixkit-player-jumping-in-a-video-game-2043.wav",
  sfx_level_clear: "/assets/audio/mixkit-video-game-treasure-2066.wav",
};

export const EMOJI_FRAMES = {
  catYellow: 0,
  catOrange: 1,
  catRed: 2,
  catPurple: 3,
  catBlue: 4,
  catGreen: 5,
  catTeal: 6,
  catPink: 7,
  catWhite: 8,
  catBlack: 9,
  check: 25,
  cross: 26,
  exclaim: 27,
  question: 28,
  leaf: 30,
  coin: 31,
  heart: 32,
  star: 33,
  apple: 70,
  pumpkin: 71,
  carrot: 72,
  mushroom: 73,
} as const;

export const SPECIAL_ICON_FRAMES = {
  starGold: 0,
  starSilver: 1,
  starBlue: 2,
  starWhite: 3,
  starPurple: 4,
  heartPink: 7,
  heartRed: 8,
  heartPurple: 9,
  gemBlue: 14,
  gemGreen: 15,
  gemPurple: 16,
  gemYellow: 17,
} as const;
